# Generated by Django 2.2.14 on 2020-07-12 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trolleyApp', '0002_auto_20200702_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trolly',
            fields=[
                ('trolley_id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('isOccupied', models.BooleanField()),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Occupied_trollies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trolly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trolleyApp.Trolly')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trolleyApp.User')),
            ],
        ),
    ]
