# Generated by Django 2.2.14 on 2020-07-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trolleyApp', '0003_auto_20200712_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trolly',
            name='isOccupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trolly',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trolly',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
