# Generated by Django 2.2.14 on 2020-07-13 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trolleyApp', '0004_auto_20200712_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupied_trollies',
            name='id',
        ),
        migrations.AddField(
            model_name='occupied_trollies',
            name='occupied_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='occupied_trollies',
            name='trolly',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trolleyApp.Trolly'),
        ),
        migrations.AlterField(
            model_name='occupied_trollies',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trolleyApp.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
