# Generated by Django 2.2.14 on 2020-07-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trolleyApp', '0005_auto_20200713_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupied_trollies',
            name='occupied_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
